export const width = 1200, height = 600;
export const slider_width = 500, slider_height = 100;
export const padding = 40;
export const margin = {top: 20, right: 80, bottom: 30, left: 70};

export let total_internal_water = new Map();
export let total_external_water = new Map();
export let total_available_water = new Map();
export let total_water_used = new Map();
export let water_stress_levels = new Map();


export const years = {
    1978: '1978-1982',
    1983: '1983-1987',
    1988: '1988-1992',
    1993: '1993-1997',
    1998: '1998-2002',
    2003: '2003-2007',
    2008: '2008-2012',
    2013: '2013-2017',
    2018: '2020',
    2030: '2030',
    2040: '2040',
};

export const display_country = {
    "Afghanistan": {display: false},
    "Albania": {display: false},
    "Algeria": {display: false},
    "Angola": {display: false},
    "Antigua-and-Barbuda": {display: false},
    "Argentina": {display: false},
    "Armenia": {display: false},
    "Australia": {display: false},
    "Austria": {display: false},
    "Azerbaijan": {display: false},
    "Bahrain": {display: false},
    "Bangladesh": {display: false},
    "Barbados": {display: false},
    "Belarus": {display: false},
    "Belgium": {display: false},
    "Belize": {display: false},
    "Benin": {display: false},
    "Bhutan": {display: false},
    "Bolivia-Plurinational-State-of": {display: false},
    "Bosnia-and-Herzegovina": {display: false},
    "Botswana": {display: false},
    "Brazil": {display: false},
    "Brunei-Darussalam": {display: false},
    "Bulgaria": {display: false},
    "Burkina-Faso": {display: false},
    "Burundi": {display: false},
    "Cabo-Verde": {display: false},
    "Cambodia": {display: false},
    "Cameroon": {display: false},
    "Canada": {display: false},
    "Central-African-Republic": {display: false},
    "Chad": {display: false},
    "Chile": {display: false},
    "China": {display: false},
    "Colombia": {display: false},
    "Comoros": {display: false},
    "Congo": {display: false},
    "Costa-Rica": {display: false},
    "Cote-dIvoire": {display: false},
    "Croatia": {display: false},
    "Cuba": {display: false},
    "Cyprus": {display: false},
    "Czechia": {display: false},
    "Democratic-People's-Republic-of-Korea": {display: false},
    "Democratic-Republic-of-the-Congo": {display: false},
    "Denmark": {display: false},
    "Djibouti": {display: false},
    "Dominica": {display: false},
    "Dominican-Republic": {display: false},
    "Ecuador": {display: false},
    "Egypt": {display: false},
    "El-Salvador": {display: false},
    "Equatorial-Guinea": {display: false},
    "Eritrea": {display: false},
    "Estonia": {display: false},
    "Ethiopia": {display: false},
    "Fiji": {display: false},
    "Finland": {display: false},
    "France": {display: false},
    "Gabon": {display: false},
    "Gambia": {display: false},
    "Georgia": {display: false},
    "Germany": {display: false},
    "Ghana": {display: false},
    "Greece": {display: false},
    "Grenada": {display: false},
    "Guatemala": {display: false},
    "Guinea": {display: false},
    "Guinea-Bissau": {display: false},
    "Guyana": {display: false},
    "Haiti": {display: false},
    "Honduras": {display: false},
    "Hungary": {display: false},
    "Iceland": {display: false},
    "India": {display: false},
    "Indonesia": {display: false},
    "Iran-Islamic-Republic-of": {display: false},
    "Iraq": {display: false},
    "Ireland": {display: false},
    "Israel": {display: false},
    "Italy": {display: false},
    "Jamaica": {display: false},
    "Japan": {display: false},
    "Jordan": {display: false},
    "Kazakhstan": {display: false},
    "Kenya": {display: false},
    "Kuwait": {display: false},
    "Kyrgyzstan": {display: false},
    "Lao-Peoples-Democratic-Republic": {display: false},
    "Latvia": {display: false},
    "Lebanon": {display: false},
    "Lesotho": {display: false},
    "Liberia": {display: false},
    "Libya": {display: false},
    "Lithuania": {display: false},
    "Luxembourg": {display: false},
    "Madagascar": {display: false},
    "Malawi": {display: false},
    "Malaysia": {display: false},
    "Maldives": {display: false},
    "Mali": {display: false},
    "Malta": {display: false},
    "Mauritania": {display: false},
    "Mauritius": {display: false},
    "Mexico": {display: false},
    "Mongolia": {display: false},
    "Morocco": {display: false},
    "Mozambique": {display: false},
    "Myanmar": {display: false},
    "Namibia": {display: false},
    "Nepal": {display: false},
    "Netherlands": {display: false},
    "New-Zealand": {display: false},
    "Nicaragua": {display: false},
    "Niger": {display: false},
    "Nigeria": {display: false},
    "Norway": {display: false},
    "Occupied-Palestinian-Territory": {display: false},
    "Oman": {display: false},
    "Pakistan": {display: false},
    "Panama": {display: false},
    "Papua-New-Guinea": {display: false},
    "Paraguay": {display: false},
    "Peru": {display: false},
    "Philippines": {display: false},
    "Poland": {display: false},
    "Portugal": {display: false},
    "Puerto-Rico": {display: false},
    "Qatar": {display: false},
    "Republic-of-Korea": {display: false},
    "Republic-of-Moldova": {display: false},
    "Romania": {display: false},
    "Russian-Federation": {display: false},
    "Rwanda": {display: false},
    "Saint-Kitts-and-Nevis": {display: false},
    "Saint-Lucia": {display: false},
    "Saint-Vincent-and-the-Grenadines": {display: false},
    "Sao-Tome-and-Principe": {display: false},
    "Saudi-Arabia": {display: false},
    "Senegal": {display: false},
    "Serbia": {display: false},
    "Sierra-Leone": {display: false},
    "Slovakia": {display: false},
    "Slovenia": {display: false},
    "Somalia": {display: false},
    "South-Africa": {display: false},
    "South-Sudan": {display: false},
    "Spain": {display: false},
    "Sri-Lanka": {display: false},
    "Sudan": {display: false},
    "Suriname": {display: false},
    "Swaziland": {display: false},
    "Sweden": {display: false},
    "Switzerland": {display: false},
    "Syrian-Arab-Republic": {display: false},
    "Tajikistan": {display: false},
    "Thailand": {display: false},
    "The-former-Yugoslav-Republic-of-Macedonia": {display: false},
    "Timor-Leste": {display: false},
    "Togo": {display: false},
    "Trinidad and Tobago": {display: false},
    "Tunisia": {display: false},
    "Turkey": {display: false},
    "Turkmenistan": {display: false},
    "Uganda": {display: false},
    "Ukraine": {display: false},
    "United-Arab-Emirates": {display: false},
    "United-Kingdom": {display: false},
    "United-Republic-of-Tanzania": {display: false},
    "United-States-of-America": {display: false},
    "Uruguay": {display: false},
    "Uzbekistan": {display: false},
    "Venezuela-Bolivarian-Republic-of": {display: false},
    "Viet-Nam": {display: false},
    "Yemen": {display: false},
    "Zambia": {display: false},
    "Zimbabwe": {display: false},
    "Greenland": {display: false}
};

