export const width = 1200, height = 600;
export const slider_width = 500, slider_height = 100;
export const padding = 40;
export const margin = {top: 20, right: 80, bottom: 30, left: 70};

export const years = {
    1978: '1978-1982',
    1983: '1983-1987',
    1988: '1988-1992',
    1993: '1993-1997',
    1998: '1998-2002',
    2003: '2003-2007',
    2008: '2008-2012',
    2013: '2013-2017',
    2018: '2020',
    2030: '2030',
    2040: '2040',
};

export const display_country = {
    "Afghanistan": {display: false},
    "Albania": {display: false},
    "Algeria": {display: false},
    "Angola": {display: false},
    "Argentina": {display: false},
    "Armenia": {display: false},
    "Australia": {display: false},
    "Austria": {display: false},
    "Azerbaijan": {display: false},
    "Bahrain": {display: false},
    "Bangladesh": {display: false},
    "Belarus": {display: false},
    "Belgium": {display: false},
    "Belize": {display: false},
    "Benin": {display: false},
    "Bhutan": {display: false},
    "Bolivia": {display: false},
    "Bosnia-and-Herzegovina": {display: false},
    "Botswana": {display: false},
    "Brazil": {display: false},
    "Brunei": {display: false},
    "Bulgaria": {display: false},
    "Burkina-Faso": {display: false},
    "Burundi": {display: false},
    "Cambodia": {display: false},
    "Cameroon": {display: false},
    "Canada": {display: false},
    "Central-African-Republic": {display: false},
    "Chad": {display: false},
    "Chile": {display: false},
    "China": {display: false},
    "Colombia": {display: false},
    "Congo": {display: false},
    "Costa-Rica": {display: false},
    "Croatia": {display: false},
    "Cuba": {display: false},
    "Czech-Republic": {display: false},
    "North-Korea": {display: false},
    "Republic-of-the-Congo": {display: false},
    "Denmark": {display: false},
    "Djibouti": {display: false},
    "Dominican-Republic": {display: false},
    "Ecuador": {display: false},
    "Egypt": {display: false},
    "El-Salvador": {display: false},
    "Equatorial-Guinea": {display: false},
    "Eritrea": {display: false},
    "Estonia": {display: false},
    "Ethiopia": {display: false},
    "Finland": {display: false},
    "France": {display: false},
    "Gabon": {display: false},
    "Gambia": {display: false},
    "Georgia": {display: false},
    "Germany": {display: false},
    "Ghana": {display: false},
    "Greece": {display: false},
    "Guatemala": {display: false},
    "Guinea": {display: false},
    "Guinea-Bissau": {display: false},
    "Guyana": {display: false},
    "Haiti": {display: false},
    "Honduras": {display: false},
    "Hungary": {display: false},
    "Iceland": {display: false},
    "India": {display: false},
    "Indonesia": {display: false},
    "Iran": {display: false},
    "Iraq": {display: false},
    "Ireland": {display: false},
    "Israel": {display: false},
    "Italy": {display: false},
    "Japan": {display: false},
    "Jordan": {display: false},
    "Kazakhstan": {display: false},
    "Kenya": {display: false},
    "Kyrgyzstan": {display: false},
    "Laos": {display: false},
    "Latvia": {display: false},
    "Lebanon": {display: false},
    "Lesotho": {display: false},
    "Liberia": {display: false},
    "Libya": {display: false},
    "Lithuania": {display: false},
    "Luxembourg": {display: false},
    "Madagascar": {display: false},
    "Malawi": {display: false},
    "Malaysia": {display: false},
    "Mali": {display: false},
    "Mauritania": {display: false},
    "Mexico": {display: false},
    "Mongolia": {display: false},
    "Morocco": {display: false},
    "Mozambique": {display: false},
    "Myanmar": {display: false},
    "Namibia": {display: false},
    "Nepal": {display: false},
    "Netherlands": {display: false},
    "New-Zealand": {display: false},
    "Nicaragua": {display: false},
    "Niger": {display: false},
    "Nigeria": {display: false},
    "Norway": {display: false},
    "Palestine": {display: false},
    "Oman": {display: false},
    "Pakistan": {display: false},
    "Panama": {display: false},
    "Papua-New-Guinea": {display: false},
    "Paraguay": {display: false},
    "Peru": {display: false},
    "Philippines": {display: false},
    "Poland": {display: false},
    "Portugal": {display: false},
    "Qatar": {display: false},
    "South-Korea": {display: false},
    "Moldova": {display: false},
    "Romania": {display: false},
    "Russia": {display: false},
    "Rwanda": {display: false},
    "Saudi-Arabia": {display: false},
    "Senegal": {display: false},
    "Serbia": {display: false},
    "Sierra-Leone": {display: false},
    "Slovakia": {display: false},
    "Slovenia": {display: false},
    "Somalia": {display: false},
    "South-Africa": {display: false},
    "South-Sudan": {display: false},
    "Spain": {display: false},
    "Sri-Lanka": {display: false},
    "Sudan": {display: false},
    "Suriname": {display: false},
    "Swaziland": {display: false},
    "Sweden": {display: false},
    "Switzerland": {display: false},
    "Syria": {display: false},
    "Tajikistan": {display: false},
    "Thailand": {display: false},
    "Macedonia": {display: false},
    "Timor-Leste": {display: false},
    "Togo": {display: false},
    "Tunisia": {display: false},
    "Turkey": {display: false},
    "Turkmenistan": {display: false},
    "Uganda": {display: false},
    "Ukraine": {display: false},
    "United-Arab-Emirates": {display: false},
    "United-Kingdom": {display: false},
    "United-Republic-of-Tanzania": {display: false},
    "United-States-of-America": {display: false},
    "Uruguay": {display: false},
    "Uzbekistan": {display: false},
    "Venezuela": {display: false},
    "Vietnam": {display: false},
    "Yemen": {display: false},
    "Zambia": {display: false},
    "Zimbabwe": {display: false}
};


const worldRegionByEntity = {
    "Afghanistan" : "Asia",
    "Albania" : "Europe",
    "Algeria" : "Africa",
    "Angola" : "Africa",
    "Argentina" : "SouthAmerica",
    "Armenia" : "Asia",
    "Australia" : "Oceania",
    "Austria" : "Europe",
    "Azerbaijan" : "Asia",
    "Bahrain" : "Asia",
    "Bangladesh" : "Asia",
    "Belarus" : "Europe",
    "Belgium" : "Europe",
    "Belize" : "NorthAmerica",
    "Benin" : "Africa",
    "Bhutan" : "Asia",
    "Bolivia" : "SouthAmerica",
    "Bosnia-and-Herzegovina" : "Europe",
    "Botswana" : "Africa",
    "Brazil" : "SouthAmerica",
    "Brunei" : "Asia",
    "Bulgaria" : "Europe",
    "Burkina-Faso" : "Africa",
    "Burundi" : "Africa",
    "Cambodia" : "Asia",
    "Cameroon" : "Africa",
    "Canada" : "NorthAmerica",
    "Central-African-Republic" : "Africa",
    "Chad" : "Africa",
    "Chile" : "SouthAmerica",
    "China" : "Asia",
    "Colombia" : "SouthAmerica",
    "Congo" : "Africa",
    "Costa-Rica" : "NorthAmerica",
    "Croatia" : "Europe",
    "Cuba" : "NorthAmerica",
    "Czech-Republic" : "Europe",
    "Republic-of-the-Congo" : "Africa",
    "Denmark" : "Europe",
    "Djibouti" : "Africa",
    "Dominican-Republic" : "NorthAmerica",
    "Ecuador" : "SouthAmerica",
    "Egypt" : "Africa",
    "El-Salvador" : "NorthAmerica",
    "Equatorial-Guinea" : "Africa",
    "Eritrea" : "Africa",
    "Estonia" : "Europe",
    "Ethiopia" : "Africa",
    "Finland" : "Europe",
    "France" : "Europe",
    "Gabon" : "Africa",
    "Gambia" : "Africa",
    "Georgia" : "Asia",
    "Germany" : "Europe",
    "Ghana" : "Africa",
    "Greece" : "Europe",
    "Guatemala" : "NorthAmerica",
    "Guinea" : "Africa",
    "Guinea-Bissau" : "Africa",
    "Guyana" : "SouthAmerica",
    "Haiti" : "NorthAmerica",
    "Honduras" : "NorthAmerica",
    "Hungary" : "Europe",
    "Iceland" : "Europe",
    "India" : "Asia",
    "Indonesia" : "Asia",
    "Iran" : "Asia",
    "Iraq" : "Asia",
    "Ireland" : "Europe",
    "Israel" : "Asia",
    "Italy" : "Europe",
    "Japan" : "Asia",
    "Jordan" : "Asia",
    "Kazakhstan" : "Asia",
    "Kenya" : "Africa",
    "Kyrgyzstan" : "Asia",
    "Laos" : "Asia",
    "Latvia" : "Europe",
    "Lebanon" : "Asia",
    "Lesotho" : "Africa",
    "Liberia" : "Africa",
    "Libya" : "Africa",
    "Lithuania" : "Europe",
    "Luxembourg" : "Europe",
    "Macedonia" : "Europe",
    "Madagascar" : "Africa",
    "Malawi" : "Africa",
    "Malaysia" : "Asia",
    "Mali" : "Africa",
    "Mauritania" : "Africa",
    "Mexico" : "NorthAmerica",
    "Moldova" : "Europe",
    "Mongolia" : "Asia",
    "Morocco" : "Africa",
    "Mozambique" : "Africa",
    "Myanmar" : "Asia",
    "Namibia" : "Africa",
    "Nepal" : "Asia",
    "Netherlands" : "Europe",
    "New-Zealand" : "Oceania",
    "Nicaragua" : "NorthAmerica",
    "Niger" : "Africa",
    "Nigeria" : "Africa",
    "North-Korea" : "Asia",
    "Norway" : "Europe",
    "Oman" : "Asia",
    "Pakistan" : "Asia",
    "Palestine" : "Asia",
    "Panama" : "NorthAmerica",
    "Papua-New-Guinea" : "Oceania",
    "Paraguay" : "SouthAmerica",
    "Peru" : "SouthAmerica",
    "Philippines" : "Asia",
    "Poland" : "Europe",
    "Portugal" : "Europe",
    "Qatar" : "Asia",
    "Romania" : "Europe",
    "Russia" : "Europe",
    "Rwanda" : "Africa",
    "Saudi-Arabia" : "Asia",
    "Senegal" : "Africa",
    "Serbia" : "Europe",
    "Sierra-Leone" : "Africa",
    "Slovakia" : "Europe",
    "Slovenia" : "Europe",
    "Somalia" : "Africa",
    "South-Africa" : "Africa",
    "South-Korea" : "Asia",
    "South-Sudan" : "Africa",
    "Spain" : "Europe",
    "Sri-Lanka" : "Asia",
    "Sudan" : "Africa",
    "Suriname" : "SouthAmerica",
    "Swaziland" : "Africa",
    "Sweden" : "Europe",
    "Switzerland" : "Europe",
    "Syria" : "Asia",
    "Tajikistan" : "Asia",
    "United-Republic-of-Tanzania" : "Africa",
    "Thailand" : "Asia",
    "Timor-Leste" : "Asia",
    "Togo" : "Africa",
    "Tunisia" : "Africa",
    "Turkey" : "Asia",
    "Turkmenistan" : "Asia",
    "Uganda" : "Africa",
    "Ukraine" : "Europe",
    "United-Arab-Emirates" : "Asia",
    "United-Kingdom" : "Europe",
    "United-States-of-America" : "NorthAmerica",
    "Uruguay" : "SouthAmerica",
    "Uzbekistan" : "Asia",
    "Venezuela" : "SouthAmerica",
    "Vietnam" : "Asia",
    "Yemen" : "Asia",
    "Zambia" : "Africa",
    "Zimbabwe" : "Africa",
};





function arr_diff (a1, a2) {

    var a = [], diff = [];

    for (var i = 0; i < a1.length; i++) {
        a[a1[i]] = true;
    }

    for (var i = 0; i < a2.length; i++) {
        if (a[a2[i]]) {
            delete a[a2[i]];
        } else {
            a[a2[i]] = true;
        }
    }

    for (var k in a) {
        diff.push(k);
    }

    return diff;
}








let arr1 = Object.keys(display_country);
let arr2 = Object.keys(worldRegionByEntity);


arr_diff(arr2, arr1).forEach(function (val) {
    console.log('"'+val+'",')
});
console.log("here")



let arr = ["British-Indian-Ocean-Territory",
    "British-Virgin-Islands",
    "Cape-Verde",
    "Cayman-Islands",
    "Channel-Islands",
    "Christmas-Island",
    "Cocos-Islands",
    "Comoros",
    "Cook-Islands",
    "Cote-dIvoire",
    "Curacao",
    "Cyprus",
    "Czechoslovakia",
    "Dominica",
    "East-Germany",
    "Eritrea-and-Ethiopia",
    "Faeroe-Islands",
    "Falkland-Islands",
    "Fiji",
    "French-Guiana",
    "French-Polynesia",
    "Gibraltar",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guernsey",
    "Hanover",
    "Hesse-Electoral",
    "Hesse-Grand-Ducal",
    "Hong-Kong",
    "Isle-of-Man",
    "Jamaica",
    "Jersey",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Liechtenstein",
    "Macao",
    "Maldives",
    "Malta",
    "Marshall-Islands",
    "Martinique",
    "Mauritius",
    "Mayotte",
    "Mecklenburg-Schwerin",
    "Micronesia-country",
    "Modena",
    "Monaco",
    "Montenegro",
    "Montserrat",
    "Nagorno-Karabakh",
    "Nauru",
    "Netherlands-Antilles",
    "New-Caledonia",
    "Niue",
    "Norfolk-Island",
    "Northern-Cyprus",
    "Northern-Mariana-Islands",
    "Palau",
    "Parma",
    "Pitcairn",
    "Puerto-Rico",
    "Republic-of-Vietnam",
    "Reunion",
    "Saint-Barthélemy",
    "Saint-Helena",
    "Saint-Kitts-and-Nevis",
    "Saint-Lucia",
    "Saint-Martin-French-part",
    "Saint-Pierre-and-Miquelon",
    "Saint-Vincent-and-the-Grenadines",
    "Samoa",
    "San-Marino",
    "Sao-Tome-and-Principe",
    "Saxony",
    "Serbia-and-Montenegro",
    "Serbia-excluding-Kosovo",
    "Seychelles",
    "Singapore",
    "Sint-Maarten-Dutch-part",
    "Solomon-Islands",
    "Somaliland",
    "South-Georgia-and-the-South-Sandwich-Islands",
    "South-Ossetia",
    "Svalbard-and-Jan-Mayen",
    "Taiwan",
    "Tokelau",
    "Tonga",
    "Transnistria",
    "Trinidad-and-Tobago",
    "Turks-and-Caicos-Islands",
    "Tuscany",
    "Tuvalu",
    "Two-Sicilies",
    "USSR",
    "United-Korea",
    "Vanuatu",
    "Vatican",
    "Wallis-and-Futuna",
    "West-Germany",
    "Western-Sahara",
    "Wuerttemburg",
    "Yemen-Arab-Republic",
    "Yemen-Peoples-Republic",
    "Yugoslavia",
    "Zanzibar"];

// Object.keys(worldRegionByEntity).forEach(function (key) {
//     if(arr.indexOf(key) === -1)
//         console.log(' "'+key.replace(/\(/g, '').replace(/\)/g, '').replace(/'/g, '').replace(/ /g, '-')+'" : "' + worldRegionByEntity[key] +'", ')
// })